config/routes.rb
Studiocracy::Application.routes.draw do
  root "pages#home"
  devise_for :users, :controllers => { omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations' }

  resources :posts, :has_many => [:comments, :post_votes]
  resources :post_votes

  resources :comments, :has_many =>[:comment_votes]
  resource  :comment_votes

  resources :charges

  resources :users

  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  get "/about", to: "pages#about", as: "about"
  get "/privacy", to: "pages#privacy", as: "privacy"
  get "/terms", to: "pages#terms", as: "terms"
  get "/our_team", to: "pages#our_team", as: "our_team"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"

  namespace :admin do
    resources :posts
    root "base#index"
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  # Markdown
  #before_save { MarkdownWriter.update_html(self) }

  has_attached_file :image, styles: { small: "64x64", med: "300x300", large: "500x500" }

  # Validations
  validates :title, presence: true, length: { maximum: 100 }, uniqueness: true
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  # Pagination
  paginates_per 30

  # Relations
  belongs_to :user
  has_many :comments
  has_many :post_votes

  # Scopes
  scope :published, lambda {
    where(draft: false)
    .order("updated_at DESC")
  }

  scope :drafted, lambda {
    where(draft: true)
    .order("updated_at DESC")
  }

  attr_reader :votecount

  def votecount
    #Ranking algorithm:
    # (Upvotes/((minutes since posted + 2)^1.8)) - (Miniscule value to break ties between 0 upvote posts)
    (((((post_votes.where(:state => 1).count))/((((Time.zone.now - created_at) / 60).round + 2) ** 1.8))) - ((Time.zone.now-created_at)/(157788000 ** 10)))
  end


end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController

  before_action :set_post, only: [
    :edit,
    :update,
    :destroy
  ]


  def dashboard
    @published_post_count = Post.published.count
    @draft_post_count = Post.drafted.count
  end

  def index
    @posts = Post.published.page(params[:page]).per(50)
  end

  def drafts
    @posts = Post.drafted.page(params[:page]).per(50)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to admin_posts_dashboard_path, notice: "New post published."
    else
      flash[:alert] = "Post not published."
      render :new
    end
  end

  def edit
  end

  def update
    @post.slug = nil
    if @post.update(post_params)
      redirect_to admin_posts_dashboard_path, notice: "Post successfully edited."
    else
      flash[:alert] = "The post was not edited."
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to admin_posts_path, notice: "The post has been deleted."
  end


  private

  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(
    :title,
    :content_md,
    :draft,
    :updated_at
    )
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def show
		@post = Post.find(params[:id])
		@comment = Comment.new
	end

	def new
		@post = Post.new
	end

	def create
		@post = current_user.posts.create(post_params)
		if @post.save
			redirect_to post_path(@post), :notice => "Post was created successfully."
		else
			render :new
		end
	end

	def destroy
		@post = post.find(params[:id])
		@post.destroy
		#redirect_to posts_path(@posts)
		flash.notice = "post '#{@post.title}' Destroyed!"

	end
	def edit
		@post = post.find(params[:id])
	end
	def update
		@post = post.find(params[:id])
		@post.update(post_params)

		flash.notice = "post '#{@post.title}' Updated!"

		#redirect_to post_path(@post)
	end

	private
	def post_params
		params.require(:post).permit(:title, :content_md, :image, :user_id, :year_created, :medium, :dimension_height, :dimension_width, :measurement, :weight_in_pounds, :price, :quantity)
	end

end

app/views/posts/_comments.html.erb
<% comment_array = @post.comments.sort_by {|comment| comment.votecount }.reverse %>
<% comment_array.each do |comment| %>
  <p><%= comment.fullname %> on <%= l(comment.created_at, format: '%B, %d %Y') %>
    <div class='votes'>
      <%= comment.up_minus_down %>
      <!--Upvoting-->
      <% if current_user && current_user.comment_votes.where(:comment_id => comment.id, :state => 1).present? %>
        <%= link_to image_tag('upvote.png'), comment_votes_path(:comment_vote => {:comment_id => comment.id, :state => 0}), :method => :post %>
        <%= link_to image_tag('icons/grey_triangle_down.png'), comment_votes_path(:comment_vote => {:comment_id => comment.id, :state => -1}), :method=> :post %>
      <% elsif current_user && current_user.comment_votes.where(:comment_id => comment.id, :state => -1).present? %>
        <%= link_to image_tag('icons/grey_triangle.png'), comment_votes_path(:comment_vote => {:comment_id => comment.id, :state => 1}), :method => :post %>
        <%= link_to image_tag('downvote.png'), comment_votes_path(:comment_vote => {:comment_id => comment.id, :state => 0}), :method => :post %>
      <% else %>
        <%= link_to image_tag('icons/grey_triangle.png'), comment_votes_path(:comment_vote => {:comment_id => comment.id, :state => 1}), :method => :post %>
        <%= link_to image_tag('icons/grey_triangle_down.png'), comment_votes_path(:comment_vote => {:comment_id => comment.id, :state => -1}), :method => :post %>
      <% end %>
    </div>
  </p>

  <blockquote>
    <p><%= comment.message %></p>
  </blockquote>
	
  <!--<button class="reply">reply</button>
  <div class="reply_box"></div>-->

<% end %>

app/views/posts/new.html.erb
<%= form_for(@post) do |f| %>
 <% if @post.errors.any? %>
 <div id="error_explanation">
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
    <div><%= msg %></div>
    <% end %>
  </ul>
</div>
<% end %>
<% end %>

<div class="col-lg-6 col-lg-offset-3 submission-form">
  <div role="form">
    <%= form_for(@post) do |f| %>
    <%= f.label :image, 'Upload a Photo of Your Work:' %>
    <%= f.file_field :image %><br />
    <%= f.label :title, "Artwork Title:" %>
    <%= f.text_field :title %><br />
    <%= f.label :content_md, "Description:" %>
    <%= f.text_field :content_md %><br />
    <%= f.label :medium, "Medium:" %>
    <%= f.select(:medium, options_for_select(['Drawing','Installation','New/Mixed Media', 'Painting','Photography','Printmaking','Sculpture'])) %>
    <br />
    <%= f.label :year_created, "Year Created:" %>
    <%= f.text_field :year_created %><br />
    <%= f.label :dimension_height, "Dimension (height):"  %>
    <%= f.text_field :dimension_height %><br />
    <%= f.label :dimension_width, "Dimension (width):"  %>
    <%= f.text_field :dimension_width %><br />
    <%= f.label :measurement, "Dimension Measurement:"  %>
    <%= f.select(:measurement, options_for_select(%w[in ft])) %><br />
    <%= f.label :weight_in_pounds, "Weight (lbs):"  %>
    <%= f.text_field :weight_in_pounds %><br />
    <%= f.label :price, "Price:"  %>
    <%= f.text_field :price %><br />
    <%= f.label :quantity, "Quantity:"  %>
    <%= f.text_field :quantity %><br />

    <div class="actions">
      <%= f.submit "Submit" %>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-sm-6">
    <h4 class="letter-spaced post-show-head"><%= @post.user.fullname.upcase %>
      <% if @post.user.city != nil && @post.user.state != nil %>
          // <%= @post.user.city.upcase %>, <%= @post.user.state.upcase %>
      <% end %>
    </h4>
  </div>
</div>

<div class="row listing post-listing shadow">
  <div class="col-md-8 col-sm-12">
    <div id="gallery" style="display:none;">

      <img alt="Image 1 Title" src=<%= @post.image.url(:large) %>
              data-image= <%= @post.image.url(:large) %>
           data-description=<%= @post.content_md %>>
    </div>


    <script type="text/javascript">
        jQuery(document).ready(function () {
            jQuery("#gallery").unitegallery();
        });
    </script>
  </div>

  <div class="col-md-4 col-sm-12 post-header">
    <h3><%= @post.title.upcase %></h3>
    <h4 class="open-sans"><%= @post.user.fullname %></h4><br/>

    <!-- Insert icons -->
    <div class="row icons-row">
      <div class='votes post-votes'>
        <%= @post.post_votes.where(:state => 1).count %>
        <% if current_user && current_user.post_votes.where(:post_id => @post.id, :state => 1).present? %>
            <%= link_to image_tag('upvote.png'), post_votes_path(:post_vote => {:post_id => @post.id, :state => 0}), :method => :post %>
        <% else %>
            <%= link_to image_tag('icons/grey_triangle.png'), post_votes_path(:post_vote => {:post_id => @post.id, :state => 1}), :method => :post %>
        <% end %>
      </div>
    </div>

    <ul class="nav nav-tabs responsive" id="myTab">
      <li class="active"><a href="#details">Details</a></li>
      <li><a href="#shipping">Shipping</a></li>
      <li><a href="#description">Description</a></li>
    </ul>

    <div class="tab-content responsive">
      <div class="tab-pane active" id="details">
        <section id="section-1">

          <% if @post.user.city != nil && @post.user.state != nil %>
              <p>Location: <%= @post.user.city.upcase %>, <%= @post.user.state.upcase %></p>
          <% end %>
          <p>Price: <span class="post-data"><%= number_to_currency(@post.price, :unit => "$") %></span></p>
          <p>Medium: <span class="post-data"> <%= @post.medium %></span></p>
          <p>Quantity: <span class="post-data"> <%= @post.quantity %></span></p>
          <p>Dimensions: <span class="post-data"> <%= @post.dimension_height %> x  <%= @post.dimension_width %> <%= @post.measurement %>.</span></p>
          <p>Weight: <span class="post-data"><%= @post.weight_in_pounds %> lbs</span></p>

          <!-- Contact modal -->
          <div id="contact-button" class="shadow"><button type="button"  data-toggle="modal" data-target="#contact-modal">
            Contact <span class="pink"><%= @post.user.first_name %></span></button></div>
          <!-- Modal -->
          <div class="modal fade" id="contact-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel">Contact <span class="pink"><%= @post.user.fullname %></span></h4>
                </div>
                <div class="modal-body">
                  <textarea class="contact-message"></textarea>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary">Send</button>
                </div>
              </div>
            </div>
          </div>

          <!-- Stripe don't touch -->
          <div id="stripe-button">
            <%= form_tag charges_path do %>
                <input type='hidden' name='post_id' value='<%= @post.id %>'/>

                <script
                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="pk_test_4YYGj3Ei4fRofFexQZH0Nfgc"
                data-image="https://s3.amazonaws.com/stripe-uploads/acct_14PR9oDe1dLPSxg5merchant-icon-1427505020708-smockLogoBlack.png"
                data-name="Studiocracy"
                data-description='<%= number_to_currency(@post.price, :unit => "$") %> for "<%= @post.title %>" by <%= @post.user.fullname %>'
                data-amount="'@post.price'">
                </script>
            <% end %>
          </div>
        </section>
      </div>
      <div class="tab-pane" id="shipping">

      </div>
      <div class="tab-pane" id="description">
        <!-- tab3 -->
        <p>
          <%= @post.content_md %>
        </p>
      </div>
    </div>

    <script type="text/javascript">

        (function($) {
            $('#myTab a').click(function (e) {
                e.preventDefault()
                $(this).tab('show')
            })

            fakewaffle.responsiveTabs(['xs', 'sm']);
        })(jQuery);
    </script>


  </div>
</div>

<!--More from artist carousel-->
<div class="more-from-artist row">
  <!--.jcarousel JQuery Carousel Plug-in-->
  <div class="wrapper shadow">
    <div class="jcarousel-wrapper">
      <h4 class="carousel-header letter-spaced">MORE FROM THIS ARTIST</h4>

      <div class="jcarousel">
        <ul>
          <% @post.user.posts.each do |post| %>
              <% if post.id != @post.id %>
                  <li>
                    <div class="post carousel-box" id="<%= post.id %>">

                      <!-- Image -->
                      <div class='carousel-image-wrapper'>
                        <%= link_to image_tag(post.image.url(:large)), post_path(post) %>
                      </div>

                      <!-- Overlay -->
                      <div class="contenthover">
                        <!-- Title -->
                        <h3><%= link_to post.title, post_path(post), class: 'post_title' %></h3>
                        <!-- Creator -->
                        <%= link_to post.user.fullname, post_path(post), class: 'artist_name' %>
                        <br/><br/>
                        <%= number_to_currency(post.price, :unit => "$") %>
                      </div>
                    </div>
                  </li>
              <% end %>
          <% end %>
        </ul>
      </div>

      <a href="#" class="jcarousel-control-prev">&lsaquo;</a>
      <a href="#" class="jcarousel-control-next">&rsaquo;</a>

      <p class="jcarousel-pagination"></p>
    </div>
  </div>
</div>

<div class="comment row">
  <%= form_for(@comment) do |f| %>
      <% if @comment.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

            <ul>
              <% @comment.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <h2>Comments:</h2>

      <div class="field">
        <%= f.text_area :message, :placeholder => "Add a comment" %>
        <%= f.hidden_field :post_id, value: @post.id %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
  <% end %>
  <div>
    <%= render :partial => 'comments', :object => @comments %>
  </div>
</div>
</div>