config/routes.rb
Studiocracy::Application.routes.draw do
  root "pages#home"
  devise_for :users, :controllers => { omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations' }

  resources :posts, :has_many => [:comments, :post_votes]
  resources :post_votes

  resources :comments, :has_many =>[:comment_votes]
  resource  :comment_votes

  resources :charges

  resources :users

  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  get "/about", to: "pages#about", as: "about"
  get "/privacy", to: "pages#privacy", as: "privacy"
  get "/terms", to: "pages#terms", as: "terms"
  get "/our_team", to: "pages#our_team", as: "our_team"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"

  namespace :admin do
    resources :posts
    root "base#index"
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
  end

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">

    <div class="row footer-first-row">

      <div class="col-xs-12 text-center fo">
        <p><small>
          &copy; <%= Time.now.year %> - Studiocracy
          <br/>
        </small></p>
      </div>

    </div>

  </div>
</div>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-61051535-1', 'auto');
ga('send', 'pageview');
</script>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
<div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('logo-header.png'), root_path, class: 'navbar-brand'%>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('logo-header.png'), root_path, class: 'navbar-brand'%>
      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#" id="browse" class="letter-spaced">BROWSE <span class="sr-only"></span></a></li>
        <!--
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        -->
      </ul>
      <%= render 'layouts/search' %>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navigation_links.html.erb
<!--<li><%= link_to "Contact", contact_path %></li>-->

<% if !user_signed_in? %>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Sign In", new_user_session_path %></li>
    <li><%= link_to "Join", new_user_registration_path %></li>
<% else %>
<!-- <li><%= link_to "Protected Page", inside_path %></li> -->
<li><%= link_to "Submit Art", new_post_path %></li>
<!-- <%= image_tag(current_user.image.url(:small)) %> -->
<%= link_to image_tag('default_icon.jpg', :width => 38, :height => 38), user_path(current_user) %>

<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
      <%= current_user.fullname %>
      <span class="caret"></span>
    </a>
	<ul class="dropdown-menu" role="menu">
		<li><%= link_to "My Profile", user_path(current_user) %> </li>
		<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
		<li><a href="#">Account Settings</a></li>
		<li><%= link_to "Sign Out", destroy_user_session_path, data:{method: :delete} %></li>
	</ul>
</li>

<% if current_user.admin? %>
<li><%= link_to "Admin", admin_root_path %></li>
<% end %>
<% end %>
<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">More <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Our Team", our_team_path %></li>
            <li><a href="#">Careers</a></li>
            <li><a href="#">Media</a></li>
            <li class="divider"></li>
            <li><%= link_to "Terms", terms_path %></li>
			<li><%= link_to "Privacy", privacy_path %></li>
            <li><%= link_to "Contact Us", contact_path %></li>
          </ul>
</li>

app/views/layouts/_search.html.erb
<form class="navbar-form navbar-left" role="search">
  <div class="form-group search-group">
    <input type="text" class="letter-spaced search-box" placeholder="SEARCH">
    <button type="submit" class="search-button">
      <%= image_tag('icons/magnifying_glass.png') %>
    </button>
  </div>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "Studiocracy" %></title>
  <%= favicon_link_tag '/favicon.ico' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<!--Start of Tawk.to Script-->
<script type="text/javascript">
  var $_Tawk_API={},$_Tawk_LoadStart=new Date();
  (function(){
    var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
    s1.async=true;
    s1.src='https://embed.tawk.to/5573f6536381c90e682dd141/default';
    s1.charset='UTF-8';
    s1.setAttribute('crossorigin','*');
    s0.parentNode.insertBefore(s1,s0);
  })();
</script>
<!--End of Tawk.to Script-->
<body>
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <div class="container">

      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>

      <div class="row">
        <div id="bodyGrid">
          <%= yield %>
        </div>
      </div>

    </div>
  </div>

  <%= render 'layouts/footer' %>

</body>
</html>